# Replace with the name which you want to give to your EKS cluster
# Cluster name can have only lowercase alphanumeric characters and hyphens
# For example: "digit-demo"
cluster_name: "demo-test"

# Name you want to give to your Database
# DB name must contain only alphanumeric characters
db_name: "dbnametest"

# Replace with DB username you want
# DB user name must contain only alphanumeric characters
db_username: "dbusertest" 

# Replace with Domain name you want for your web applications
domain_name: "demotest.digit.org"

# Replace with the name you want to give to your S3 bucket which is used to store the terraform state
terraform_state_bucket_name: "demotest-state-s3-bucket"

public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpqN5ftlQLeQNMv7leuHYtpq8kp0BzvqBnB4ndNw5F9Q5WRejLoogrPesDJ7xc3q7ExYLUDKOtCJAEw21AOiTgX92UOnZ4YxAeTPau5ac0PE/lXfDIABn/5tbIrrOhDc18Jq1ylN09i6nkVSAsM5L5nCtNzgNaBpSjUdvwBcZwCMSHu6Wg4t7T/0x3uNLKKW1XrOhXzZ8/1tx8dubQfz0NOJxrWqVI9H5c06PnlViBdLYpsB7+cLhg/SKn7e7G1qNbpy/sOLLwbr88/fADNExZxQfisXho500wLiGmsaQFaRVbxQnFC1L3PvY4FZtMWWeYn5iTruBWBqXOXvG3w24N"

tenant_id: "statea"
