# Replace with the name which you want to give to your EKS cluster
# Cluster name can have only lowercase alphanumeric characters and hyphens
# For example: "digit-demo"
cluster_name: "pgroneclicknew"
ssh_key_name: "pgr"
# Name you want to give to your Database
# DB name must contain only alphanumeric characters
db_name: "pgroneclickdb"

# Replace with DB username you want
# DB user name must contain only alphanumeric characters
db_username: "pgroneclick" 

# Replace with Domain name you want for your web applications
domain_name: "pgroneclick.digit.org"

# Replace with the name you want to give to your S3 bucket which is used to store the terraform state
terraform_state_bucket_name: "pgroneclick-state-s3-bucket"

public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0nU4OrwqQL9d/F3Q4mEx7nj9D9v7inW6NYkUTl8lEOqXq6m2XXwsb5wgAGYEMiPKPFigml4y2ek8ovZ4GYBv0AtrF8y1JP/pm/KiRVmXVxOJ0ba3C0xhZvH3iXUjB2tVeCkOzQZNAvyLe5rRalVE9dW7FZr4ihRDy2mZoy+lq30p4eFy0LagvEEqymRlQ6AlHNyeH0FpDiyW4pHmDvAuLhIgZf70DQ+/PNU08qwutdxykjzb3/iNI4wIWEDh79cqcK4arlSSLutzFyX3NW0WtltHlkZpX67C+lFjJFHPwMT8n8OvHL9MzcACBC42Rh9MTsyLFCgW7mYXPu8F2aOGF"

tenant_id: "statea"
