# Replace with the name which you want to give to your EKS cluster
# Cluster name can have only lowercase alphanumeric characters and hyphens
# For example: "digit-demo"
cluster_name: "pgroneclicknew"
ssh_key_name: "pgr"
# Name you want to give to your Database
# DB name must contain only alphanumeric characters
db_name: "pgroneclickdb"

# Replace with DB username you want
# DB user name must contain only alphanumeric characters
db_username: "pgroneclick" 

# Replace with Domain name you want for your web applications
domain_name: "pgroneclick.digit.org"

# Replace with the name you want to give to your S3 bucket which is used to store the terraform state
terraform_state_bucket_name: "pgroneclick-state-s3-bucket"

public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCSwl7kJKehv2TYyrFivgDRZwh0iNA5NAvNM7xjQdjeMXSUKRrWAVPDSH6lKgUwpb95FuNgXXZ/Hh8BKEp3m2Et+T9otSMvH+aKt+Cg9iUAbd4u9njimoajKT5RCwtYZJrPWP4WMxtZl0kK3Z2zINYfJsmsiKJEguhvQbM0Vm1NJ7/4u1oj0PoMhP3twi37ED/1bE2iy7/jay9s3UQVN5nltfaxeuhnrOqRw4Sk4u/Vo7AZPYiTq9cU2WdL21cbucKKosp7KmXpvBOpCrP9UcPXcV6YFYWdyAYjmZYDPLKXUiJV0P6Tg+BlbO/Z7/oJ+S8POsbcn7ThA9ugVP3swVyv"

tenant_id: "statea"
